PDC.Web/Pages/Answers/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PDC.Web.Models;

namespace PDC.Web.Pages.Answers
{
    public class CreateModel : PageModel
    {
        private readonly PDC.Web.Models.PDCContext _context;

        public CreateModel(PDC.Web.Models.PDCContext context)
        {
            _context = context;
        }
        public IList<tAnswer> answers { get; set; }
        public tQuestion question { get; set; }
        //public IActionResult OnGet()
        //{
        //    //ViewData["questions"] = new SelectList(_context.tQuestion, "question_id", "province_name");
        //    return Page();
        //}
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            answers = await _context.tAnswer.Where(a => a.question_id == id).AsNoTracking().ToListAsync();
            question = await _context.tQuestion.SingleOrDefaultAsync(m => m.question_id == id);

            if (question == null)
            {
                return NotFound();
            }
            return Page();
        }
        [BindProperty]
        public tAnswer tAnswer { get; set; }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            tAnswer.question_id = (int)id;
            tAnswer.create_by = "System";
            tAnswer.create_date = DateTime.Now;
            tAnswer.edit_by = "System";
            tAnswer.edit_date = DateTime.Now;
            _context.tAnswer.Add(tAnswer);
            await _context.SaveChangesAsync();

            return Redirect("/Answers/Create?id=" + id);
        }
    }
}

PDC.Web/Pages/Answers/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PDC.Web.Models;

namespace PDC.Web.Pages.Answers
{
    public class DetailsModel : PageModel
    {
        private readonly PDC.Web.Models.PDCContext _context;

        public DetailsModel(PDC.Web.Models.PDCContext context)
        {
            _context = context;
        }

        public tAnswer tAnswer { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            tAnswer = await _context.tAnswer.SingleOrDefaultAsync(m => m.answer_id == id);

            if (tAnswer == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

PDC.Web/Pages/Applicants/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using PDC.Web.Data;
using PDC.Web.Models;
using static PDC.Web.Models.tApplicant;

namespace PDC.Web.Pages.Applicants
{
    public class CreateModel : PageModel
    {
        private readonly PDC.Web.Models.PDCContext _context;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public CreateModel(PDC.Web.Models.PDCContext context, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        public IActionResult OnGet()
        {
            ViewData["client"] = new SelectList(_context.tClient, "client_id", "client_name");
            ViewData["city"] = new SelectList(_context.tCity, "city_id", "city_name");
            return Page();
        }

        [BindProperty]
        public tApplicant tApplicant { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            //if (!ModelState.IsValid)
            //{
            //    return Page();
            //}
            if (_context.tApplicant.Any(a => a.email == tApplicant.email)) {
                return RedirectToPage("");
            }
            else
            {
                var user = await _userManager.GetUserAsync(User);
                tApplicant.create_by = user.UserName;
                tApplicant.create_date = DateTime.Now;
                tApplicant.edit_by = user.UserName;
                tApplicant.status = "Approved";
                tApplicant.edit_date = DateTime.Now;
                tApplicant.last_login = DateTime.MaxValue;
                _context.tApplicant.Add(tApplicant);
                await _context.SaveChangesAsync();

                return RedirectToPage("./Index");
            }
            
        }
    }
}

PDC.Web/Pages/Applicants/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PDC.Web.Data;
using PDC.Web.Models;

namespace PDC.Web.Pages.Applicants
{
    public class DetailsModel : PageModel
    {
        private readonly PDC.Web.Models.PDCContext _context;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public DetailsModel(PDC.Web.Models.PDCContext context)
        {
            _context = context;
        }

        public tApplicant tApplicant { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            tApplicant = await _context.tApplicant.SingleOrDefaultAsync(m => m.applicant_id == id);

            if (tApplicant == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

PDC.Web/Pages/Batches/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PDC.Web.Data;
using PDC.Web.Models;

namespace PDC.Web.Pages.Batches
{
    public class CreateModel : PageModel
    {
        private readonly PDC.Web.Models.PDCContext _context;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public CreateModel(PDC.Web.Models.PDCContext context, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        public IActionResult OnGet()
        {
            ViewData["applicants"] = new SelectList(_context.tApplicant, "applicant_id", "full_name");
            ViewData["programs"] = new SelectList(_context.tProgram, "program_id", "program_name");
            ViewData["clients"] = new SelectList(_context.tClient, "client_id", "client_name");
            var user = _userManager.GetUserName(User);
            userName = user;
            return Page();
        }

        [BindProperty]
        public tApplicantProgram tApplicantProgram { get; set; }
        [BindProperty]
        public tBatch tBatch { get; set; }
        [BindProperty]
        public string userName { get; set; }
        public IList<tApplicant> applicants { get; set; }
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            tBatch.approval_status = "Requested";
            _context.tBatch.Add(tBatch);
            await _context.SaveChangesAsync();
            
            return RedirectToPage("./Index");
        }
    }
}

PDC.Web/Pages/Batches/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PDC.Web.Models;

namespace PDC.Web.Pages.Batches
{
    public class DetailsModel : PageModel
    {
        private readonly PDC.Web.Models.PDCContext _context;

        public DetailsModel(PDC.Web.Models.PDCContext context)
        {
            _context = context;
        }

        public tBatch tBatch { get; set; }
        
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            tBatch = await _context.tBatch
                .Include(t => t.client).SingleOrDefaultAsync(m => m.batch_id == id);

            if (tBatch == null)
            {
                return NotFound();
            }
            else
            {
                tBatch.applicantPrograms = await _context.tApplicantProgram.Where(ap => ap.batch_id == tBatch.batch_id).ToListAsync();
                tBatch.client = await _context.tClient.Where(c => c.client_id == tBatch.client_id).SingleOrDefaultAsync();
                for(int i = 0; i < tBatch.applicantPrograms.Count; i++)
                {
                    tBatch.applicantPrograms[i].applicant = await _context.tApplicant.Where(a => a.applicant_id == tBatch.applicantPrograms[i].applicant_id).SingleOrDefaultAsync();
                    tBatch.applicantPrograms[i].program = await _context.tProgram.Where(p => p.program_id == tBatch.applicantPrograms[i].program_id).SingleOrDefaultAsync();
                }
            }
            return Page();
        }
    }
}

PDC.Web/Pages/Batches/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PDC.Web.Data;
using PDC.Web.Models;

namespace PDC.Web.Pages.Batches
{
    public class IndexModel : PageModel
    {
        private readonly PDC.Web.Models.PDCContext _context;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public IndexModel(PDC.Web.Models.PDCContext context, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        public string nameSort { get; set; }
        public string genderSort { get; set; }
        public string currentSort { get; set; }

        public IList<tBatch> batches { get; set; }
        public static tBatch batchTemp { get; set; }
        public async Task OnGetAsync()
        {
            batches = await _context.tBatch.Include(c => c.client).Where(b => b.isExpired == false).ToListAsync();

            for(int i = 0; i < batches.Count; i++)
            {
                batches[i].applicantPrograms = await _context.tApplicantProgram.Include(a => a.applicant).Include(p => p.program).Where(ap => ap.batch_id == batches[i].batch_id).ToListAsync();
                //// get applicants list
                //for (int j = 0; j < batches[i].applicantPrograms.Count; j++)
                //{
                //    batches[i].applicantPrograms[j].applicant = await _context.tApplicant.SingleOrDefaultAsync(a => a.applicant_id == batches[i].applicantPrograms[j].applicant_id);
                //    batches[i].applicantPrograms[j].program = await _context.tProgram.SingleOrDefaultAsync(p => p.program_id == batches[i].applicantPrograms[j].program_id);
                //}
                //// get client data
                //batches[i].client = await _context.tClient.SingleOrDefaultAsync(c => c.client_id == batches[i].client_id);

            }

            //switch (sortOrder)
            //{
            //    case "first_desc":
            //        batches = batches.OrderByDescending(b => b.applicantPrograms);break;
            //    case "gender_desc":
            //        batches = batches.OrderByDescending(b => b.gender);break;
            //    case "Gender":
            //        batches = batches.OrderBy(b => b.gender);break;
            //    default:
            //        batches = batches.OrderBy(b => b.last_name);break;
            //}
            //Batches = await batches.ToListAsync();
            //IList<tApplicantProgram> temp;
            //temp = await _context.tApplicantProgram.AsNoTracking().ToListAsync();

            //foreach (tApplicantProgram ap in temp)
            //{
            //    tApplicant apl = _context.tApplicant.SingleOrDefault(a => a.applicant_id == ap.applicant_id);
            //    tClient clt = _context.tClient.SingleOrDefault(c => c.client_id == apl.client_id);
            //    apl.client = new tClient();
            //    apl.client = clt;
            //    ap.applicant = new tApplicant();
            //    ap.applicant = apl;
            //}
            //var smt = (from baru in _context.tApplicantProgram
            //           select new Batch()
            //           { client_name = baru.applicant.client.client_name, batch_name = baru.batch_name, program_id = baru.program_id, approval_status = baru.approval_status, approved_by = baru.approved_by, approved_date = baru.approved_date, batch_start = baru.batch_start, batch_end = baru.batch_end }).Distinct();
            //batch = await smt.AsNoTracking().ToListAsync();
        }

        public async Task<IActionResult> OnPostRejectAsync(int ID)
        {
            var user = await _userManager.GetUserAsync(User);
            tBatch batch = await _context.tBatch.SingleOrDefaultAsync(b => b.batch_id == ID);
            batchTemp = batch;
            _context.Attach(batch).State = EntityState.Modified;
            batch.approval_status = "Rejected";
            batch.isExpired = true;
            batch.approved_date = DateTime.Now.ToString("dd MMM yyyy HH:mm");
            batch.approved_by = user.UserName;
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
        public async Task<IActionResult> OnPostApproveAsync(int ID)
        {
            var user = await _userManager.GetUserAsync(User);
            tBatch batch = await _context.tBatch.SingleOrDefaultAsync(b => b.batch_id == ID);
            _context.Attach(batch).State = EntityState.Modified;
            batch.approval_status = "Approved";
            batch.approved_date = DateTime.Now.ToString("dd MMM yyyy HH:mm");
            batch.approved_by = user.UserName;
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

PDC.Web/Pages/Cities/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using PDC.Web.Models;

namespace PDC.Web.Pages.Cities
{
    public class CreateModel : PageModel
    {
        private readonly PDC.Web.Models.PDCContext _context;

        public CreateModel(PDC.Web.Models.PDCContext context)
        {
            _context = context;
        }
        private class Area
        {
            public string Name { get; set; }
            public int Time { get; set; }
        }
        public IActionResult OnGet()
        {
            ViewData["province"] = new SelectList(_context.tProvince, "province_id", "province_name");
            
            List<Area> area = new List<Area>();
            Area a = new Area();
            a.Name = "WIB";
            a.Time = 0;
            area.Add(a);
            a = new Area();
            a.Name = "WITA";
            a.Time = 1;
            area.Add(a);
            a = new Area();
            a.Name = "WIT";
            a.Time = 2;
            area.Add(a);
            ViewData["time_area"] = new SelectList(area, "Time", "Name");
            return Page();
        }

        [BindProperty]
        public tCity tCity { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            tCity.create_by = "System";
            tCity.create_date = DateTime.Now;
            tCity.edit_by = "System";
            tCity.edit_date = DateTime.Now;
            _context.tCity.Add(tCity);
            await _context.SaveChangesAsync();
            return RedirectToPage("");
            //return RedirectToPage("./Index");
        }
    }
}

PDC.Web/Pages/Batches/Details.cshtml
@page
@model PDC.Web.Pages.Batches.DetailsModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Pages/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>tBatch</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tBatch.batch_name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tBatch.batch_name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tBatch.approval_status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tBatch.approval_status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tBatch.approved_by)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tBatch.approved_by)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tBatch.approved_date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tBatch.approved_date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tBatch.batch_start)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tBatch.batch_start)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tBatch.batch_end)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tBatch.batch_end)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tBatch.create_by)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tBatch.create_by)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tBatch.create_date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tBatch.create_date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tBatch.edit_by)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tBatch.edit_by)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tBatch.edit_date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tBatch.edit_date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tBatch.client)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tBatch.client.address1)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.tBatch.batch_id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

PDC.Web/Pages/Batches/Index.cshtml
@page
@model PDC.Web.Pages.Batches.IndexModel
@section header{
    <style type="text/css">
        .Requested {
            background-color: grey;
            color: #fff;
        }

        .Approved {
            background-color: green;
            color: #fff;
        }

        .Rejected {
            background-color: red;
            color: #fff;
        }

        .Pending {
            background-color: lime;
            color: #fff;
        }
    </style>
    <style>
        .panel-heading {
            padding: 0;
            border: 0;
        }

        .panel-title > a, .panel-title > a:active {
            display: block;
            padding: 15px;
            color: #555;
            font-size: 16px;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 1px;
            word-spacing: 3px;
            text-decoration: none;
        }
    </style>
    <script>
        $('.panel-collapse').on('show.bs.collapse', function () {
            $(this).siblings('.panel-heading').addClass('active');
        });

        $('.panel-collapse').on('hide.bs.collapse', function () {
            $(this).siblings('.panel-heading').removeClass('active');
        });
    </script>
}
@{
    ViewData["Title"] = "Batches";
}

<h2>Batches List</h2>

<p>
    <a asp-page="Create">Create New</a>
</p>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="false">

    @{int rowNum = 0; }
    @foreach (var item in Model.batches)
    {
    <div class="panel panel-default">
        @{rowNum += 1;}
        <div class="panel-heading " role="tab" id="heading_@rowNum">
            <h4 class="panel-title">
                <a class="collapse-link" role="button" data-toggle="collapse" data-parent="#accordion" href='#collapse_@rowNum' aria-expanded="true" aria-controls="collapseOne"><i class="fa fa-chevron-right"></i> @item.batch_name</a>
            </h4>
            <table class="table" style="margin-bottom:0px;">
                <tbody>
                    <tr>
                        <td>Client Name: @item.client.client_name</td>
                        @if (item.approval_status == "Requested")
                        {
                            <td>Approval Status: <label class="label-info">&nbsp;@item.approval_status&nbsp;</label></td>
                        }
                        else if (item.approval_status == "Approved")
                        {
                            <td>Approval Status: <label class="label-success">&nbsp;@item.approval_status&nbsp;</label></td>
                        }
                        else
                        {
                            <td>Approval Status: <label class="label-danger">&nbsp;@item.approval_status&nbsp;</label></td>
                        }
                        <td>Approved By: @item.approved_by</td>
                        @if (item.approved_date != "9999-31-12T23:59:59")
                        {
                            <td>@item.approved_date</td>
                        }
                        else
                        {
                            <td></td>
                        }
                        <td>Batch Start: <label class="label-info">&nbsp;@item.batch_start.ToString("dd MMM yy HH:mm")&nbsp;</label></td>
                        <td>Batch End: <label class="label-info">&nbsp;@item.batch_end.ToString("dd MMM yy HH:mm")&nbsp;</label></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div id='collapse_@rowNum' class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_@rowNum">
            <div class="panel-body">
                @if (item.approval_status == "Requested")
                {
                    <div class="row">
                        <form method="post">
                            <div class="col-md-2">
                                <input type="submit" value="Approve" class="btn btn-warning" asp-route-id="@item.batch_id" asp-page-handler="Approve" onclick="return confirm('Are you sure you want to approve @item.batch_name?');" />
                            </div>
                            <div class="col-md-2">
                                <input type="submit" value="Reject" class="btn btn-danger" asp-route-id="@item.batch_id" asp-page-handler="Reject" onclick="return confirm('Are you sure you want to reject @item.batch_name?');" />
                            </div>
                        </form>
                    </div>
                }
                <div class="row">
                    <div class="col-md-12">
                    </div>
                </div>
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <td>Program</td>
                            <td><a asp-page="./Index" asp-route-sortOrder="@Model.nameSort">Applicant</a></td>
                            <td><a asp-page="./Index" asp-route-sortOrder="@Model.genderSort">Gender</a></td>
                            <td>e-mail</td>
                            <td>Date of Birth</td>
                            <td>Age</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var itm in item.applicantPrograms)
                        {
                            <tr>
                                <td>@itm.program.program_name</td>
                                <td>@itm.applicant.full_name</td>
                                @if (itm.applicant.gender == 0)
                                {
                                    <td>Male</td>
                                }
                                else
                                {
                                    <td>Female</td>
                                }
                                <td>@itm.applicant.email</td>
                                <td>@itm.applicant.dob.ToString("dd MMM yy")</td>
                                <td>
                                    @{
                                        int umur = (DateTime.Now - itm.applicant.dob).Days;
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    }
</div>
    